apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: angular-run-
  namespace: default
spec:
  pipelineRef:
    name: ci-pipeline
  params:
  - name: app-name
    value: angular-app
  - name: image-tag
    value: v1
  taskRunTemplate:
    serviceAccountName: tekton-sa
