apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: angular-pipeline
  namespace: default
spec:
  params:
    - name: image-tag
      type: string
      default: latest
  workspaces:
    - name: shared-workspace
  tasks:
    # Step 1: Clone source code
    - name: clone-source
      taskRef:
        name: git-clone
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: repo-url
          value: https://github.com/shrutiiimehra7/gitops-app-repo.git
        - name: branch
          value: main

    # Step 2: Build and push Docker image (npm build happens inside Dockerfile)
    - name: build-push
      taskRef:
        name: docker-build-push
      runAfter: [clone-source]
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: image-name
          value: angular-frontend
        - name: image-tag
          value: $(params.image-tag)
        - name: context-path
          value: angular-frontend

    # Step 3: Update manifest
    - name: update-manifest
      taskRef:
        name: update-manifest
      runAfter: [build-push]
      params:
        - name: image-name
          value: angular-frontend
        - name: image-tag
          value: $(params.image-tag)
        - name: service-name
          value: angular-frontend
        - name: manifests-repo
          value: https://github.com/shrutiiimehra7/gitops-manifests-repo.git
