apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: ci-pipeline
  namespace: default
spec:
  params:
  - name: app-name
    type: string
    description: App to build and deploy
  - name: image-tag
    type: string
    default: "v1"

  tasks:
  - name: build-push
    taskRef:
      name: build-and-push
    params:
    - name: app-name
      value: $(params.app-name)
    - name: image-tag
      value: $(params.image-tag)

  - name: deploy
    taskRef:
      name: deploy-app
    runAfter:
    - build-push
    params:
    - name: app-name
      value: $(params.app-name)
    - name: image-tag
      value: $(params.image-tag)
