apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: angular-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://gitops:gitops123@192.168.49.2:30329/gitops/gitops-project.git
    targetRevision: HEAD
    path: k8s/angular-app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
